apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: zbju73put-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe:4349b829a8b7e93fd0849bc5ebf93345e7309444@sha256:09f9a7c31b4eb8290fadd60c08f681f602b90b0ecfa38e2e146a9e5300ad8b3b
        name: container-image  
